### PR TITLE
fix build failure due to the following convertion:

### PR DESCRIPTION
**Pull request by goldenrye**
src/polycubed/src/rest_server.cpp:130:71: error: invalid conversion from ‘int (*)(int, void*)’ to ‘int (*)(int, X509_STORE_CTX*)

### CODE REVIEW

**Comment by mauriciovasquezbernal** [comment]
Hello @goldenrye, could you please verify that you are using the right version of pistache? (It is https://github.com/oktal/pistache/)

I haven't seen that error, that looks weird as the signature of `client_verify_callback` is `int (int, void *)` [1] and that's the same that `useSSLAuth` requires [2] 

[1] https://github.com/polycube-network/polycube/blob/master/src/polycubed/src/rest_server.h#L67
[2] https://github.com/oktal/pistache/blob/6aa428674a66c1adebc4e3527d1ac1f7dd10230b/include/pistache/endpoint.h#L115.

**Comment by mauriciovasquezbernal** [comment]
@goldenrye any updated on this?

**Comment by mauriciovasquezbernal** [comment]
@goldenrye ping.

**Comment by goldenrye** [comment]
Will verify that today.

- Jianwen

**Comment by goldenrye** [comment]
The pistache version is too old, after pulling latest pistache, the issue is gone, so close the PR.

**Pull request closed without merging**
