### PR TITLE
Documentation: update list of dependencies

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
Dependencies in the installation guide were not aligned with the ones in
scripts/install.sh.

Solves: #143

### CODE REVIEW

**Comment by mauriciovasquezbernal** [comment]
> @mauriciovasquezbernal
> Apart from the one you updated, it's also looking for below dependency packages.
> Is it possible to verify in bare metal installation in your lab or VM with minimal package selection?
> 
>     1. netperf
> 
>     2. arping
> 
>     3. openssl
> 
>     4. LuaJIT

AFAIK those are recommended but not necessary, are you getting warnings or errors on those?

**Comment by acloudiator** [comment]
> AFAIK those are recommended but not necessary, are you getting warnings or errors on those?

I'm getting errors:

~/polycube/build$ cmake .. -DENABLE_PCN_IPTABLES=ON
```
-- Version is pre_transparent_services+ [git: (branch/commit): master/79429777]
-- Latest recognized Git tag is -128-NOTFOUND
-- Git HEAD is 79429777c3b0afab3dc8770ed3b0b1b3bcac4558
-- Revision is 128-NOTFOUND-79429777
-- Found LLVM: /usr/lib/llvm-5.0/include 5.0.1
-- Using static-libstdc++
-- Could NOT find LuaJIT (missing: LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenSSL.cmake:390 (find_package_handle_standard_args)
  src/polycubed/src/CMakeLists.txt:5 (find_package)
```

**Comment by frisso** [comment]
@mauriciovasquezbernal OpenSSL should be needed for the secure web server (in polycubed), isn't it?

**Comment by mauriciovasquezbernal** [comment]
@frisso that should be provided by libssl-dev, I am not sure why OpenSSL is requested.

**Comment by acloudiator** [comment]
Updated procedure LGTM and worked well. Tested in Local VM.

**Pull request merged**
