### PR TITLE
Bcc-static linked at compile time for Polycubed already includes the …

### PR DESCRIPTION
**Pull request by l30006821**
…LLVM static library.At runtime polycubed links clang again, clang links the dynamic library of LLVM, causing LLVM to report error: "Option XXXXXX registered more than once"

issue:https://github.com/polycube-network/polycube/issues/335

I can't think of a better way. Do you have any better Suggestions?

### CODE REVIEW

**Comment by l30006821** [comment]
I can't see why the build failed. How can I check?

**Comment by goldenrye** [comment]
what's the version of LLVM and clang running into this issue?

**Comment by l30006821** [comment]
llvm version:10.0.1
clang version:10.0.1

**Comment by l30006821** [comment]
What should I do now?

**Comment by frisso** [comment]
Superseded by #370

**Pull request closed without merging**
