### PR TITLE
Polycube on BCC v0.12.0

### PR DESCRIPTION
**Pull request by sebymiano**
This PR attempts to update Polycube to support the newest (stable) version of BCC (i.e., 0.12.0).
Right now, it is cloning my personal fork of BCC with the changes required to support the latest version and make it working with Polycube.

Please `DO NOT` merge it, right now the only purpose is to check if all the tests are passing; then, we can think to upstream the changes.

### CODE REVIEW

**Comment by palexster** [comment]
Hi @sebymiano! If everything is going ok as it seems can we proceed with the PR on https://github.com/polycube-network/bcc ? In fact, the new LTS is in two months and I think we have to get rid of those old dependencies as soon as we can.

**Comment by sebymiano** [comment]
@palexster if the others did not find any problem I guess we can merge it.
I have created a PR on the BCC branch; once it is merged there I can modify this PR accordingly.

**Comment by palexster** [comment]
Awesome!

**Comment by palexster** [comment]
Ref. polycube-network/bcc#6

**Comment by sebymiano** [comment]
This PR should be now ready to be merged.

**Pull request merged**
